export { Client } from './client.model';
export { Login } from './login.model';
export { User } from './user.model';
export { Adicionais } from './adicionais.model';
export { Cabecalho } from './cabecalho.model';
export { Experiencia } from './experiencia.model';
export { Formacao } from './formacao.model';
export { Habilidades } from './habilidades.model';
export { Curriculo } from './curriculo.model';
